pipeline { 
 agent any
 //parameters {
   // choice(
     // name: 'Env',
      //choices: ['dev','prod'],
      //description: 'Passing the Environment'
    //)
  //}
  stages{
     stage("terraform init and apply on Dev Enironemnt"){
       steps {
          sh "pwd;cd terraform"
          sh returnStatus: true, script: 'terraform workspace new dev'
          sh "terraform workspace select dev"
          sh "terraform init"
          sh 'pwd; cd terraform; terraform init; terraform apply -var-file dev.tfvars -auto-approve'
       }
     }
   stage("ansible playbook excutions"){
       steps {
         sh 'pwd; cd terraform; ansible-playbook -i one.txt test.yml'
       }
     }
   stage("cleaning the disk space"){
       steps {
         sh 'docker image prune'
       }
     }
  }
}
