pipeline { 
 agent any
 parameters {
    choice(
      name: 'Env',
      choices: ['dev','prod'],
      description: 'Passing the Environment'
    )
  }
  stages{
     stage("terraform init and apply on Dev Enironemnt"){
       steps {
          sh "pwd;cd terraform"
          sh returnStatus: true, script: 'terraform workspace new dev'
          sh "terraform workspace select dev"
          sh "terraform init"
          sh 'pwd; cd terraform; terraform apply -var-file "${Env}.tfvars" -auto-approve'
       }
     }
     stage("terraform init and apply on Prd Enironemnts"){
       steps {
          sh "pwd;cd terraform"
          sh returnStatus: true, script: 'terraform workspace new prod'
          sh "terraform workspace select prod"
          sh "terraform init"
        sh "pwd; cd terraform; terraform apply -var-file ${Env}.tfvars -auto-approve"
       }
     }
  }
}
