pipeline { 
 agent any
  stages{
     stage("terraform init and apply on Dev Enironemnt"){
       steps {
          sh "pwd;cd terraform"
          sh returnStatus: true, script: 'terraform workspace new dev'
          sh "pwd; cd terraform; terraform workspace select dev"
          sh "pwd; cd terraform; terraform init"
          sh "pwd; cd terraform; terraform apply -var-file=dev.tfvars -auto-approve"
       }
     }
     stage("terraform init and apply on Prd Enironemnt"){
       steps {
          sh "pwd;cd terraform"
          sh returnStatus: true, script: 'terraform workspace new prod'
          sh "pwd; cd terraform; terraform workspace select prod"
          sh "pwd; cd terraform; terraform init"
          sh "pwd; cd terraform; terraform apply -var-file=prod.tfvars -auto-approve"
       }
     }
  }
}
